import type { AISettings } from '../src/types/ai';

/** 供 SceneForge direct_llm 集成测试使用的最小合法 AISettings */
export const MOCK_LLM_SETTINGS: AISettings = {
  llmProviders: [
    {
      id: 'test-provider',
      name: 'Test',
      type: 'openai_compatible',
      baseUrl: 'https://api.example.com/v1',
      apiKey: 'test-key',
      models: ['test-model'],
      enableThinking: false,
    },
  ],
  defaultProviderId: 'test-provider',
  defaultModel: 'test-model',
  llmBaseUrl: '',
  llmApiKey: '',
  llmModel: '',
  enableThinking: false,
  jimengApiUrl: '',
  jimengSessionId: '',
  jimengModel: 'jimeng',
  minimaxApiKey: '',
  minimaxVoiceId: 'male-qn-qingse',
  minimaxSpeed: 1,
  minimaxVol: 1,
  minimaxPitch: 0,
  minimaxEmotion: '',
  minimaxModel: 'speech-2.8-hd',
  ttsProviders: [],
  defaultTtsProviderId: null,
  defaultTtsVoiceId: null,
  ttsVoices: [],
  imageProviders: [],
  defaultImageProviderId: null,
  defaultImageModel: null,
  globalCoverImagePrompt: '',
  videoProviders: [],
  defaultVideoProviderId: null,
  defaultVideoModel: null,
  promptBindings: {},
  cardGenerationConcurrency: 2,
  defaultStylePresetId: 'default',
};